source 'https://rubygems.org'

gem 'rails', '3.2.2'

gem 'gravatar_image_tag','0.1.0'
gem 'execjs'
gem 'therubyracer'
gem 'mysql2'
gem "will_paginate", :git => "https://github.com/p7r/will_paginate.git", :branch => "rails3"
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'


  gem 'uglifier', '>= 1.0.3'
end

gem 'prototype-rails'

group :development do
  gem "rspec-rails", "~> 2.6"
  gem 'faker' , '0.3.1'
 
end
group :test do
  gem "rspec-rails", "~> 2.6"
 gem "annotate", "~> 2.4.0"
 gem 'factory_girl_rails','~>1.0'
end